[project]
name = "english-game"
version = "0.1.0"
description = ""
authors = [
    {name = "Trung Tran",email = "tritrungtq@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "flask (>=3.1.2,<4.0.0)",
    "flask-injector (>=0.15.0,<0.16.0)",
    "injector (>=0.22.0,<0.23.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "flask-cors (>=6.0.1,<7.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "flask-jwt-extended (>=4.7.1,<5.0.0)",
    "psutil (>=7.1.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
